databases:
  - name: playcode-db
    databaseName: playcode
    user: playcode
    plan: free

services:
  - type: web
    name: playcode-web
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    healthCheckPath: /
    autoDeploy: true
    preDeployCommand: /app/bin/playcode eval Playcode.Release.migrate
    envVars:
      - key: PHX_SERVER
        value: "true"
      - key: MIX_ENV
        value: prod
      - key: POOL_SIZE
        value: "10"
      - key: DATABASE_URL
        fromDatabase:
          name: playcode-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: OTEL_TRACES_EXPORTER
        value: none
